"""Reusable ACDS PDF report generation service."""

import json
import uuid
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


DISCLAIMER = (
    "This report was generated by ACDS to assist SOC analysts in security monitoring "
    "and incident review. Final investigation, validation, and response decisions "
    "should be performed by authorized security personnel."
)


def classify_agent(action: str) -> str:
    text = action.lower()
    if "detection" in text:
        return "Detection Agent"
    if any(token in text for token in ("evidence", "feature", "explain", "pe-header", "pe header")):
        return "Explainability Agent"
    if any(token in text for token in ("response", "recommended", "quarantine", "isolate")):
        return "Response Agent"
    if any(token in text for token in ("report", "persisted")):
        return "Report Agent"
    return "Orchestrator Agent"


def incident_to_log_rows(incident: Dict[str, Any]) -> List[Dict[str, Any]]:
    actions = incident.get("actions_taken") or []
    if isinstance(actions, str):
        actions = [actions]
    if not actions:
        actions = ["Incident recorded"]

    timestamp = (
        incident.get("timestamp")
        or incident.get("created_at")
        or incident.get("detected_at")
        or "Unknown"
    )
    incident_id = incident.get("incident_id") or incident.get("threat_id") or "Unknown"
    rows = []
    for index, action in enumerate(actions):
        action_text = str(action) if action else "Unknown"
        rows.append({
            "id": f"{incident_id}-{index}",
            "timestamp": timestamp,
            "created_at": incident.get("created_at") or timestamp,
            "incident_id": incident_id,
            "module": incident.get("module") or incident.get("threat_type") or "Unknown",
            "agent": classify_agent(action_text),
            "action": action_text,
            "severity": incident.get("severity") or "Unknown",
            "status": incident.get("status") or incident.get("lifecycle_state") or "Unknown",
            "lifecycle_state": incident.get("lifecycle_state") or incident.get("status") or "Unknown",
        })
    return rows


class ACDSReportPDFService:
    """Generate professional PDF reports from incidents and audit logs."""

    def __init__(self, reports_dir: Optional[Path] = None):
        project_root = Path(__file__).resolve().parents[2]
        self.project_root = project_root
        self.incidents_path = project_root / "data" / "incidents.json"
        self.reports_dir = reports_dir or project_root / "reports" / "generated"
        self.reports_dir.mkdir(parents=True, exist_ok=True)
        self.metadata_path = self.reports_dir / "reports_metadata.json"

    def get_report_types(self) -> List[Dict[str, str]]:
        return [
            {
                "type": "threat_summary",
                "name": "Threat Summary",
                "description": "Overview of detected threats, modules, severities, and SOC actions",
            },
            {
                "type": "detection_analysis",
                "name": "Detection Analysis",
                "description": "Analysis of detection evidence, model output, and module coverage",
            },
            {
                "type": "incident_log",
                "name": "Incident Log",
                "description": "Chronological incident details and audit trail",
            },
            {
                "type": "performance_metrics",
                "name": "Performance Metrics",
                "description": "Operational metrics derived from available incidents and logs",
            },
            {
                "type": "executive_summary",
                "name": "Executive Summary",
                "description": "Management-level security posture summary",
            },
            {
                "type": "compliance_report",
                "name": "Compliance Report",
                "description": "Compliance-oriented evidence and response summary",
            },
        ]

    def generate_report(
        self,
        report_type: str,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        include_details: bool = True,
    ) -> Dict[str, Any]:
        now = datetime.now(timezone.utc)
        end_date = self._ensure_aware(end_date) or now
        start_date = self._ensure_aware(start_date) or (end_date - timedelta(days=7))
        normalized_type = self._normalize_report_type(report_type)

        incidents = [
            incident for incident in self.load_incidents()
            if self._incident_in_range(incident, start_date, end_date)
        ]
        logs = self.build_logs(incidents)
        summary = self.build_summary(incidents, logs, normalized_type)

        report_id = f"RPT-{uuid.uuid4().hex[:10].upper()}"
        generated_at = now.isoformat()
        file_name = f"acds_{normalized_type}_{report_id}.pdf"
        file_path = self.reports_dir / file_name

        self._build_pdf(
            file_path=file_path,
            report_id=report_id,
            report_type=normalized_type,
            generated_at=generated_at,
            start_date=start_date,
            end_date=end_date,
            incidents=incidents,
            logs=logs,
            summary=summary,
            include_details=include_details,
        )

        metadata = {
            "report_id": report_id,
            "report_type": normalized_type,
            "generated_at": generated_at,
            "file_name": file_name,
            "filename": file_name,
            "filepath": str(file_path),
            "download_url": f"/api/v1/reports/incidents/{report_id}/download",
            "status": "generated",
            "date_range": {
                "start_date": start_date.isoformat(),
                "end_date": end_date.isoformat(),
            },
            "summary": summary,
        }
        self._append_metadata(metadata)
        return metadata

    def list_reports(self, limit: int = 50) -> List[Dict[str, Any]]:
        reports = self._load_metadata()
        reports.sort(key=lambda item: item.get("generated_at", ""), reverse=True)
        return reports[:limit]

    def get_report(self, report_id: str) -> Optional[Dict[str, Any]]:
        for report in self._load_metadata():
            if report.get("report_id") == report_id:
                return report
        return None

    def get_report_path(self, report_id: str) -> Optional[Path]:
        report = self.get_report(report_id)
        if not report:
            return None
        path = Path(report.get("filepath", ""))
        if path.exists() and path.is_file():
            return path
        fallback = self.reports_dir / report.get("file_name", "")
        return fallback if fallback.exists() else None

    def delete_report(self, report_id: str) -> bool:
        records = self._load_metadata()
        report = next((item for item in records if item.get("report_id") == report_id), None)
        if not report:
            return False
        path = self.get_report_path(report_id)
        if path and path.exists():
            path.unlink()
        records = [item for item in records if item.get("report_id") != report_id]
        with self.metadata_path.open("w", encoding="utf-8") as handle:
            json.dump(records, handle, indent=2)
        return True

    def load_incidents(self) -> List[Dict[str, Any]]:
        if not self.incidents_path.exists():
            return []
        try:
            with self.incidents_path.open("r", encoding="utf-8") as handle:
                data = json.load(handle)
        except Exception as exc:
            print(f"Failed to read incidents for report generation: {exc}")
            return []
        incidents = data.get("incidents", []) if isinstance(data, dict) else []
        return incidents if isinstance(incidents, list) else []

    def build_logs(self, incidents: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        rows: List[Dict[str, Any]] = []
        for incident in incidents:
            rows.extend(incident_to_log_rows(incident))
        rows.sort(key=lambda row: row.get("timestamp") or "", reverse=True)
        return rows

    def build_summary(
        self,
        incidents: List[Dict[str, Any]],
        logs: List[Dict[str, Any]],
        report_type: str,
    ) -> Dict[str, Any]:
        modules = Counter(str(item.get("module") or "Unknown").lower() for item in incidents)
        severities = Counter(str(item.get("severity") or "Unknown").upper() for item in incidents)
        states = Counter(str(item.get("lifecycle_state") or item.get("status") or "Unknown").lower() for item in incidents)
        ransomware_count = modules.get("ransomware", 0)
        threat_count = sum(1 for item in incidents if item.get("prediction") not in {"SAFE", None})

        return {
            "title": self._title_for_type(report_type),
            "total_incidents": len(incidents),
            "total_audit_events": len(logs),
            "threat_count": threat_count,
            "module_breakdown": dict(modules),
            "severity_breakdown": dict(severities),
            "state_breakdown": dict(states),
            "executive_summary": self._analyst_summary(incidents, logs, ransomware_count, threat_count),
            "analyst_notes": self._analyst_notes(incidents, logs),
            "recommended_actions": self._recommended_actions(incidents),
        }

    def _build_pdf(
        self,
        file_path: Path,
        report_id: str,
        report_type: str,
        generated_at: str,
        start_date: datetime,
        end_date: datetime,
        incidents: List[Dict[str, Any]],
        logs: List[Dict[str, Any]],
        summary: Dict[str, Any],
        include_details: bool,
    ) -> None:
        doc = SimpleDocTemplate(
            str(file_path),
            pagesize=letter,
            rightMargin=0.55 * inch,
            leftMargin=0.55 * inch,
            topMargin=0.55 * inch,
            bottomMargin=0.55 * inch,
        )
        styles = getSampleStyleSheet()
        title = ParagraphStyle(
            "ACDSTitle",
            parent=styles["Title"],
            alignment=TA_CENTER,
            fontSize=18,
            textColor=colors.HexColor("#0f172a"),
            spaceAfter=10,
        )
        section = ParagraphStyle(
            "ACDSSection",
            parent=styles["Heading2"],
            fontSize=13,
            textColor=colors.HexColor("#0f766e"),
            spaceBefore=12,
            spaceAfter=8,
        )
        normal = ParagraphStyle("ACDSNormal", parent=styles["BodyText"], fontSize=9, leading=12)
        small = ParagraphStyle("ACDSSmall", parent=styles["BodyText"], fontSize=8, leading=10)

        story: List[Any] = []
        story.append(Paragraph("ACDS — Autonomous Cyber Defense System", title))
        story.append(Paragraph("Professional SOC Incident and Detection Report", normal))
        story.append(Spacer(1, 0.15 * inch))

        story.append(self._table([
            ["Report ID", report_id],
            ["Report Type", summary["title"]],
            ["Generated At", generated_at],
            ["Date Range", f"{start_date.isoformat()} to {end_date.isoformat()}"],
            ["Status", "Generated"],
        ], [1.5 * inch, 5.3 * inch]))

        story.append(Paragraph("Executive Summary", section))
        story.append(Paragraph(self._escape(summary["executive_summary"]), normal))

        story.append(Paragraph("Detection Overview by Module", section))
        story.append(self._counter_table(summary["module_breakdown"], "Module", "Incidents"))

        story.append(Paragraph("Severity Breakdown", section))
        story.append(self._counter_table(summary["severity_breakdown"], "Severity", "Count"))

        story.append(Paragraph("Incident Details Table", section))
        incident_rows = [["Incident ID", "Module", "Severity", "Status", "Prediction", "Created"]]
        for incident in incidents[:25]:
            incident_rows.append([
                self._short(incident.get("incident_id") or "Unknown", 18),
                incident.get("module") or "Unknown",
                incident.get("severity") or "Unknown",
                incident.get("lifecycle_state") or incident.get("status") or "Unknown",
                incident.get("prediction") or "Unknown",
                self._short(incident.get("created_at") or "Unknown", 22),
            ])
        if len(incident_rows) == 1:
            incident_rows.append(["No incidents", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown"])
        story.append(self._table(incident_rows, [1.25 * inch, 0.9 * inch, 0.8 * inch, 1.0 * inch, 0.95 * inch, 1.9 * inch], header=True, font_size=7))

        story.append(Paragraph("Evidence / Indicators", section))
        evidence_items = []
        for incident in incidents[:12]:
            for item in (incident.get("evidence") or [])[:3]:
                evidence_items.append(f"{incident.get('incident_id', 'Unknown')}: {item}")
        story.extend(self._bullet_block(evidence_items or ["No evidence indicators were available in the selected range."], small))

        story.append(Paragraph("Recommended SOC Actions", section))
        story.extend(self._bullet_block(summary["recommended_actions"], normal))

        story.append(Paragraph("Audit Trail", section))
        audit_rows = [["Time", "Incident ID", "Agent", "Action", "Status"]]
        for row in logs[:30]:
            audit_rows.append([
                self._short(row.get("timestamp") or "Unknown", 20),
                self._short(row.get("incident_id") or "Unknown", 16),
                row.get("agent") or "Unknown",
                self._short(row.get("action") or "Unknown", 34),
                row.get("status") or row.get("lifecycle_state") or "Unknown",
            ])
        if len(audit_rows) == 1:
            audit_rows.append(["Unknown", "Unknown", "Unknown", "No audit events available", "Unknown"])
        story.append(self._table(audit_rows, [1.35 * inch, 1.05 * inch, 1.25 * inch, 2.35 * inch, 0.8 * inch], header=True, font_size=6.5))

        story.append(Paragraph("Analyst Notes", section))
        story.extend(self._bullet_block(summary["analyst_notes"], normal))

        story.append(Paragraph("Disclaimer", section))
        story.append(Paragraph(DISCLAIMER, small))

        doc.build(story)

    def _table(self, rows: List[List[Any]], col_widths: List[float], header: bool = False, font_size: float = 8) -> Table:
        escaped_rows = [[Paragraph(self._escape(str(cell)), getSampleStyleSheet()["BodyText"]) for cell in row] for row in rows]
        table = Table(escaped_rows, colWidths=col_widths, repeatRows=1 if header else 0)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0 if header else -1), colors.HexColor("#e2e8f0") if header else colors.HexColor("#f8fafc")),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#0f172a")),
            ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#cbd5e1")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold" if header else "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), font_size),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        return table

    def _counter_table(self, values: Dict[str, int], first_header: str, second_header: str) -> Table:
        rows = [[first_header, second_header]]
        if values:
            rows.extend([[key.replace("_", " ").title(), count] for key, count in sorted(values.items())])
        else:
            rows.append(["Unknown", 0])
        return self._table(rows, [3.2 * inch, 1.2 * inch], header=True)

    def _bullet_block(self, items: List[str], style: ParagraphStyle) -> List[Any]:
        story: List[Any] = []
        for item in items[:20]:
            story.append(Paragraph(f"- {self._escape(str(item))}", style))
            story.append(Spacer(1, 0.04 * inch))
        return story

    def _append_metadata(self, metadata: Dict[str, Any]) -> None:
        records = self._load_metadata()
        records.append(metadata)
        with self.metadata_path.open("w", encoding="utf-8") as handle:
            json.dump(records, handle, indent=2)

    def _load_metadata(self) -> List[Dict[str, Any]]:
        if not self.metadata_path.exists():
            return []
        try:
            with self.metadata_path.open("r", encoding="utf-8") as handle:
                data = json.load(handle)
        except Exception:
            return []
        return data if isinstance(data, list) else []

    @staticmethod
    def _ensure_aware(value: Optional[datetime]) -> Optional[datetime]:
        if value is None:
            return None
        if value.tzinfo is None:
            return value.replace(tzinfo=timezone.utc)
        return value

    @staticmethod
    def _normalize_report_type(value: str) -> str:
        return str(value or "threat_summary").replace("-", "_").lower()

    @staticmethod
    def _title_for_type(report_type: str) -> str:
        return report_type.replace("_", " ").title()

    def _incident_in_range(self, incident: Dict[str, Any], start: datetime, end: datetime) -> bool:
        raw = incident.get("created_at") or incident.get("timestamp") or incident.get("detected_at")
        if not raw:
            return True
        try:
            parsed = datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
            parsed = self._ensure_aware(parsed)
        except Exception:
            return True
        return start <= parsed <= end

    @staticmethod
    def _analyst_summary(incidents: List[Dict[str, Any]], logs: List[Dict[str, Any]], ransomware_count: int, threat_count: int) -> str:
        if not incidents:
            return (
                "No incidents were recorded in the selected period. ACDS telemetry remains available "
                "for monitoring, and SOC analysts should continue routine validation of detection coverage."
            )
        return (
            f"ACDS reviewed {len(incidents)} incidents and {len(logs)} audit events in the selected period. "
            f"{threat_count} incidents were classified as active threats or non-safe predictions. "
            f"Ransomware accounted for {ransomware_count} incident records. The audit trail shows static analysis, "
            "evidence extraction, and response-oriented actions suitable for analyst review."
        )

    @staticmethod
    def _analyst_notes(incidents: List[Dict[str, Any]], logs: List[Dict[str, Any]]) -> List[str]:
        if not incidents:
            return ["No incident records were available for the selected reporting window."]
        notes = [
            "Validate high-severity incidents before closure.",
            "Confirm static-analysis-only findings before allowing any executable sample to run.",
            "Review audit events for missing response ownership or unresolved lifecycle states.",
        ]
        if any(str(item.get("lifecycle_state", "")).lower() == "analysis_failed" for item in incidents):
            notes.append("Some samples failed feature extraction; verify file integrity and model artifact availability.")
        return notes

    @staticmethod
    def _recommended_actions(incidents: List[Dict[str, Any]]) -> List[str]:
        actions: List[str] = []
        for incident in incidents:
            actions.extend(incident.get("recommended_actions") or [])
        if not actions:
            return [
                "Continue SOC monitoring and periodic report review.",
                "Run controlled simulations to validate data collection and response workflows.",
            ]
        deduped = []
        for action in actions:
            if action not in deduped:
                deduped.append(action)
        return deduped[:12]

    @staticmethod
    def _short(value: Any, length: int) -> str:
        text = str(value)
        return text if len(text) <= length else f"{text[: length - 3]}..."

    @staticmethod
    def _escape(value: str) -> str:
        return (
            str(value)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )


_service: Optional[ACDSReportPDFService] = None


def get_acds_report_pdf_service() -> ACDSReportPDFService:
    global _service
    if _service is None:
        _service = ACDSReportPDFService()
    return _service
